### PR TITLE
Corrected 'remote add upstream' command

### PR DESCRIPTION
**Pull request by ansel2000**
Saw a small mistake in the 5th step of creating a pull request and corrected it. It should be 'OriginalUserName' not 'YourUserName'.

### CODE REVIEW

**Comment by deliciafernandes** [comment]
cool 'OriginalUserName' also works. Thanks @ansel2000 😃

**Comment by Kaif10** [comment]
Hey Ansel, 'YourUserName'  is used in most of  the blog posts instead of  'OriginalUserName'. So its okay I guess.

**Comment by ansel2000** [comment]
Well if it works then I guess it's fine. Usually the original owners link is used.
https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github

Since the pull request part of the repo was based on https://opensource.com/article/19/7/create-pull-request-github
and the above syntax was also followed there I assumed that "yourusername" wouldn't work. Maybe a mistake on my part. 

But its all good. 🙂 @Kaif10

**Comment by deliciafernandes** [comment]
@ansel2000 thanks for pointing it out though 😃

**Pull request closed without merging**
