### PR TITLE
added a new meme

### PR DESCRIPTION
**Pull request by DoraTheExplorax**

### CODE REVIEW

**Comment by deliciafernandes** [comment]
Hey @DoraTheExplorax thanks for the contribution, can you please add the image in the README.md as well 😃

**Comment by DoraTheExplorax** [comment]
Where exactly in readme do you want me to put the meme?

**Comment by deliciafernandes** [comment]
Add it to the README.md file as well and will merge it right away.

**Comment by DoraTheExplorax** [comment]
> Hey @DoraTheExplorax thanks for the contribution, can you please add the image in the README.md as well 😃 

Where do you exactly want me to put the meme in the readme.md ?

**Comment by deliciafernandes** [comment]
> Where exactly in readme do you want me to put the meme?
[link to the readme.md](https://github.com/CSI-SFIT/Getting-Started-With-Hacktoberfest/blob/main/Meme%20Catalogue/README.md)

At the end would work.

**Comment by DoraTheExplorax** [comment]
made the changes

**Comment by deliciafernandes** [comment]
Great! Merged! 😌

**Pull request merged**
